version: "3"

services:
  nexus-1:
    container_name: nexus-1
    hostname: nexus-1
    image: repo-nexus.kavosh.org:8110/sonatype/nexus3:3.70.1
    restart: always
      #    environment:
      #      - INSTALL4J_ADD_VM_PARAMS="-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/some-other-dir"
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:8081:8081
      - 0.0.0.0:8082:8082
      - 0.0.0.0:8101:8101 # Docker DE Host
      - 0.0.0.0:8102:8102 # Docker DE Group
      
      - 0.0.0.0:8111:8111 # Docker DEVOPS Host
      - 0.0.0.0:8112:8112 # Docker DEVOPS Group

      - 0.0.0.0:8121:8121 # Docker DS Host
      - 0.0.0.0:8122:8122 # Docker DS Group

      - 0.0.0.0:8131:8131 # Docker SE Host
      - 0.0.0.0:8132:8132 # Docker SE Group

      # - 0.0.0.0:8141:8141 ##Docker Reseve Host
      # - 0.0.0.0:8142:8142 ##Docker Reseve Group

      - 0.0.0.0:8191:8191 # Docker arman Host
      # - 0.0.0.0:8192:8192 ##Docker Reseve Group
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/nexus/nexus-data:/nexus-data
    cpus: 4
    mem_limit: 4g
      #    healthcheck:
      #      test: curl -s http://localhost:8081/api/pub/status | grep Success
        #      interval: 60s
        #      timeout: 3s
        #      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "1"   # number of files or file count
        max-size: "300m" # file size

          #    networks:
          #      - kvsh-overlay
          #networks:
          #  kvsh-overlay:
          #    name: kvsh-overlay
          #    driver: overlay
          #    attachable: true

  nexus-nginx:
    image: repo-nexus.kavosh.org:8110/nginx:bookworm
    #image: repo-nexus.kavosh.org:8080/nginx:stable-bullseye
    container_name: nexus-nginx
    restart: unless-stopped
    ports:
      - 8888:8888
      - 8889:8889
      - 8091:8091
      - 8100:8100 # Docker DE Group
      - 8110:8110 # Docker DEVOPS Group
      - 8120:8120 # Docker DS Group
      - 8130:8130 # Docker SE Group
      - 8190:8190 # Docker arman Group
      - 80:80
      - 443:443
    volumes:
      - /data/nexus/nginx-conf/conf.d/nexus.conf:/etc/nginx/conf.d/nexus.conf
      - /data/nexus/ssl:/ssl/
      - /data/nexus/certs:/etc/ssl/certs
